%%
%% Autogenerated by Thrift Compiler (1.0.0-dev)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(shared_types).

-include("shared_types.hrl").

-export([struct_info/1, struct_info_ext/1, enum_info/1, enum_names/0, struct_names/0, exception_names/0]).

struct_info('SharedStruct') ->
  {struct, [{1, i32},
          {2, string}]}
;

struct_info('SharedException') ->
  {struct, [{1, string},
          {2, i32}]}
;

struct_info(_) -> erlang:error(function_clause).

struct_info_ext('SharedStruct') ->
  {struct, [{1, undefined, i32, 'key', undefined},
          {2, undefined, string, 'value', undefined}]}
;

struct_info_ext('SharedException') ->
  {struct, [{1, undefined, string, 'message', undefined},
          {2, undefined, i32, 'code', undefined}]}
;

struct_info_ext(_) -> erlang:error(function_clause).

struct_names() ->
  ['SharedStruct'].

enum_info(_) -> erlang:error(function_clause).

enum_names() ->
  [].

exception_names() ->
  ['SharedException'].

