%%
%% Autogenerated by Thrift Compiler (1.0.0-dev)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(simple_service_thrift).
-behaviour(thrift_service).


-include("simple_service_thrift.hrl").

-export([struct_info/1, function_info/2, function_names/0]).

struct_info(_) -> erlang:error(function_clause).
%%% interface
% echo_user(This, User)
function_info('echo_user', params_type) ->
  {struct, [{1, {struct, {'simple_types', 'User'}}}]}
;
function_info('echo_user', reply_type) ->
  {struct, {'simple_types', 'User'}};
function_info('echo_user', exceptions) ->
  {struct, []}
;
% ping(This)
function_info('ping', params_type) ->
  {struct, []}
;
function_info('ping', reply_type) ->
  bool;
function_info('ping', exceptions) ->
  {struct, []}
;
function_info(_Func, _Info) -> erlang:error(function_clause).

function_names() -> 
  ['echo_user', 'ping'].

